#+TITLE: SMPE_1920
#+AUTHOR: Anderson Mattheus Maliszewski
#+STARTUP: overview indent
#+TAGS: noexport(n) deprecated(d)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+SEQ_TODO: TODO(t!) STARTED(s!) WAITING(w!) | DONE(d!) CANCELLED(c!) DEFERRED(f!)

This is the repository for the 
*Scientic Methodology and Performance Evaluation for Experimental
Computer* class, in which are located the
files and scripts used to perform the proposed final work
activity. Above are descrived the files and folders. Further details
about the experiments are described in [[./LabBook.org]].

* BATCH
Here are contained the execution and system information collection
 scripts.

*  LOGS
This folder have the logs of the benchmarks execution in a CSV file,
both machine files used by the MPI execution line and the environment
information about the nodes used in the experiments in a ORG file.

** BACKUP
In this folder are contained the backup logs about each application
and interconnection.

* NPB3.4
This is the folder of the *Nas Parallel Benchmarks (NPB)* in which are
the MPI executables are compiled.

* R
This folder have the *Design of Experiments (DoE)* script in a R file,
which was used to create the experimental project in a CSV file, used
to randomly execute the binaries of the NPB.

*  LabBook.org
In this file are described the objective of this work, as well as, the
step-by-step of the enterire project.

