#+TITLE: SMPE_1920
#+AUTHOR: Anderson Mattheus Maliszewski
#+STARTUP: overview indent
#+TAGS: noexport(n) deprecated(d)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+SEQ_TODO: TODO(t!) STARTED(s!) WAITING(w!) | DONE(d!) CANCELLED(c!) DEFERRED(f!)

This repository is for the 
*Scientific Methodology and Performance Evaluation for Experimental
Computer* class, in which are located the
files and scripts used to perform the proposed final work
activity. Above are described the files and folders. Further details
about the experiments are described in [[./LabBook.org]].

- BATCH
Here are contained the execution and system information collection scripts.
- LOGS
This folder has the logs of the benchmarks execution in a CSV file,
both machine files used by the MPI execution line and the environment
information about the nodes used in the experiments in an ORG file.
- LOGS/BACKUP
In this folder are contained the backup logs about each application
and interconnection.
- NPB3.4
This folder has the *Nas Parallel Benchmarks (NPB)* in which are
the MPI executables are compiled.
- R
This folder has the *Design of Experiments (DoE)* script in an R file,
which was used to create the experimental project in a CSV file, used
to execute the binaries of the NPB randomly.
- LabBook.org
In this file are described the objective of this work, as well as, the
step-by-step of the entire project.

